use llmignore::sync::{sync, SyncStatus};
use std::fs;
use tempfile::tempdir;

#[test]
fn sync_writes_tool_ignore_files() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::write(root.join(".llmignore"), "node_modules/\n.env\n").unwrap();

    let results = sync(root, false).unwrap();
    assert!(!results.is_empty(), "should write at least one tool file");

    let cursor = fs::read_to_string(root.join(".cursorignore")).unwrap();
    assert!(
        cursor.contains("node_modules/"),
        "rules copied into .cursorignore"
    );
    assert!(
        cursor.contains("Generated by llmignore"),
        "generated header present so re-sync can overwrite safely"
    );
}

#[test]
fn sync_errors_without_llmignore() {
    let dir = tempdir().unwrap();
    assert!(sync(dir.path(), false).is_err(), "sync needs a .llmignore");
}

#[test]
fn sync_skips_user_owned_files_without_force() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::write(root.join(".llmignore"), "node_modules/\n").unwrap();
    fs::write(root.join(".cursorignore"), "my custom rule\n").unwrap();

    let results = sync(root, false).unwrap();

    assert_eq!(
        fs::read_to_string(root.join(".cursorignore")).unwrap(),
        "my custom rule\n",
        "must not clobber a hand-written file without --force"
    );
    assert!(
        results
            .iter()
            .any(|r| r.filename == ".cursorignore" && r.status == SyncStatus::SkippedExists),
        "the skip should be reported"
    );
}

#[test]
fn sync_force_overwrites_user_files() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::write(root.join(".llmignore"), "node_modules/\n").unwrap();
    fs::write(root.join(".cursorignore"), "my custom rule\n").unwrap();

    sync(root, true).unwrap();
    assert!(fs::read_to_string(root.join(".cursorignore"))
        .unwrap()
        .contains("node_modules/"));
}

#[test]
fn sync_overwrites_its_own_previous_output_without_force() {
    let dir = tempdir().unwrap();
    let root = dir.path();
    fs::write(root.join(".llmignore"), "node_modules/\n").unwrap();
    sync(root, false).unwrap();
    // change source and re-sync without --force; generated file should update
    fs::write(root.join(".llmignore"), "dist/\n").unwrap();
    sync(root, false).unwrap();
    let cursor = fs::read_to_string(root.join(".cursorignore")).unwrap();
    assert!(
        cursor.contains("dist/"),
        "re-sync updates its own generated file"
    );
}
