//! Embedded default `.llmignore` content and sensitive-file detection patterns.
//!
//! `DEFAULT_LLMIGNORE` is written verbatim by `llmignore init` and is also used as
//! a fallback ruleset when a repository has no `.llmignore` of its own. Keeping a
//! single source means "defaults" and "what init writes" can never drift apart.

/// Default ruleset, in standard gitignore syntax.
pub const DEFAULT_LLMIGNORE: &str = r#"# .llmignore - tells AI tools (Claude, Cursor, Copilot, ...) what NOT to read.
# Same syntax as .gitignore. Generated by `llmignore init`. Edit freely.

# ── Secrets & credentials (never send these to an LLM) ──
.env
.env.*
!.env.example
!.env.sample
!.env.template
*.pem
*.key
*.p12
*.pfx
*.keystore
id_rsa
id_dsa
id_ecdsa
id_ed25519
*.ppk
.npmrc
.pypirc
.netrc
.htpasswd
secrets.*
credentials.*
*.secret
.aws/
.ssh/
.gnupg/
service-account*.json
gha-creds-*.json
auth.json
.git-credentials
.pgpass
.dockercfg
kubeconfig
*.kubeconfig
*.jks
*.p8
*.ovpn
terraform.tfstate
terraform.tfstate.backup
*.tfvars

# ── Dependencies & vendored code ──
node_modules/
bower_components/
jspm_packages/
vendor/
.pnp.*
.yarn/
__pycache__/
.venv/
venv/
env/
.tox/
site-packages/
target/
.cargo/
Pods/
.gradle/
.m2/

# ── Build output & artifacts ──
dist/
build/
out/
.next/
.nuxt/
.svelte-kit/
.output/
.vercel/
.netlify/
.turbo/
coverage/
.nyc_output/
*.o
*.a
*.so
*.dylib
*.dll
*.exe
*.class
*.pyc
*.pyo
*.wasm

# ── Caches ──
.cache/
.parcel-cache/
.eslintcache
.stylelintcache
.pytest_cache/
.mypy_cache/
.ruff_cache/
.sass-cache/

# ── Lockfiles (huge, low signal for reasoning) ──
package-lock.json
yarn.lock
pnpm-lock.yaml
bun.lockb
Cargo.lock
poetry.lock
Pipfile.lock
composer.lock
Gemfile.lock
go.sum

# ── Minified / generated / sourcemaps ──
*.min.js
*.min.css
*.map
*.bundle.js

# ── Binaries, archives & large media ──
*.zip
*.tar
*.tar.gz
*.tgz
*.gz
*.rar
*.7z
*.jar
*.war
*.bin
*.iso
*.dmg
*.png
*.jpg
*.jpeg
*.gif
*.webp
*.avif
*.ico
*.bmp
*.tiff
*.svg
*.pdf
*.mp3
*.mp4
*.mov
*.avi
*.mkv
*.webm
*.wav
*.flac
*.ttf
*.otf
*.woff
*.woff2
*.eot
*.psd
*.ai
*.sketch
*.fig

# ── Data dumps (often large / non-instructive) ──
*.sqlite
*.sqlite3
*.db
*.parquet
*.avro

# ── Logs & temp ──
*.log
logs/
*.tmp
*.temp
*.swp
*.swo
*.pid
*.seed
*.bak

# ── IDE / editor / OS junk ──
.idea/
.vscode/
.history/
.DS_Store
Thumbs.db
desktop.ini

# ── Version control internals ──
.git/
.hg/
.svn/
"#;

/// Globs (gitignore syntax) that, when present and NOT already ignored, indicate a
/// likely secret leaking into AI context. Used by `llmignore scan`.
pub const SENSITIVE_PATTERNS: &[(&str, &str)] = &[
    (
        ".env",
        "Environment file - commonly holds API keys and DB passwords",
    ),
    (
        ".env.*",
        "Environment file - commonly holds API keys and DB passwords",
    ),
    ("*.pem", "Private key / certificate"),
    ("*.key", "Private key"),
    ("*.p12", "PKCS#12 keystore"),
    ("*.pfx", "PKCS#12 keystore"),
    ("id_rsa", "SSH private key"),
    ("id_dsa", "SSH private key"),
    ("id_ecdsa", "SSH private key"),
    ("id_ed25519", "SSH private key"),
    ("*.ppk", "PuTTY private key"),
    (".npmrc", "npm config - may contain auth tokens"),
    (".pypirc", "PyPI config - may contain credentials"),
    (".netrc", "netrc - stores login credentials"),
    (".htpasswd", "HTTP auth password file"),
    ("credentials.*", "Credentials file"),
    ("secrets.*", "Secrets file"),
    ("*.secret", "Secret file"),
    ("service-account*.json", "GCP service account key"),
    ("*.keystore", "Java keystore"),
    ("*.jks", "Java keystore"),
    ("*.p8", "Apple / PKCS#8 private key"),
    ("auth.json", "Auth file - may contain tokens"),
    (
        ".git-credentials",
        "Git credential store (plaintext URLs with passwords)",
    ),
    (".pgpass", "PostgreSQL password file"),
    (".dockercfg", "Docker registry credentials"),
    ("kubeconfig", "Kubernetes config - cluster credentials"),
    ("*.kubeconfig", "Kubernetes config - cluster credentials"),
    ("*.ovpn", "OpenVPN profile - may embed keys"),
    (
        "terraform.tfstate",
        "Terraform state - often holds plaintext secrets",
    ),
    (
        "terraform.tfstate.backup",
        "Terraform state backup - often holds plaintext secrets",
    ),
    (
        "*.tfvars",
        "Terraform variables - frequently hold credentials",
    ),
];
