//! Mirror `.llmignore` into the ignore files that AI tools respect *today*.
//!
//! No assistant reads `.llmignore` natively yet, but most respect their own
//! gitignore-style file. `sync` writes those from the single `.llmignore` source so
//! "one file" really does cover every tool.

use anyhow::{bail, Context, Result};
use std::path::Path;

/// Marker written at the top of every generated file. Its presence means llmignore
/// owns the file and may overwrite it on the next sync.
pub const GENERATED_HEADER: &str =
    "# Generated by llmignore from .llmignore - edit .llmignore instead, then run `llmignore sync`.";

/// A tool-specific ignore file that uses gitignore syntax.
pub struct Target {
    pub filename: &'static str,
    pub tool: &'static str,
}

/// The ignore files llmignore knows how to generate.
pub const TARGETS: &[Target] = &[
    Target {
        filename: ".cursorignore",
        tool: "Cursor",
    },
    Target {
        filename: ".codeiumignore",
        tool: "Windsurf / Codeium",
    },
    Target {
        filename: ".aiexclude",
        tool: "Gemini Code Assist",
    },
    Target {
        filename: ".geminiignore",
        tool: "Gemini CLI",
    },
    Target {
        filename: ".aiderignore",
        tool: "Aider",
    },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncStatus {
    Written,
    SkippedExists,
}

#[derive(Debug, Clone)]
pub struct SyncOutcome {
    pub filename: &'static str,
    pub tool: &'static str,
    pub status: SyncStatus,
}

/// Generate every tool ignore file from `<root>/.llmignore`.
///
/// Files that already exist and were NOT generated by llmignore are skipped unless
/// `force` is set, so a user's hand-written ignore file is never silently clobbered.
pub fn sync(root: &Path, force: bool) -> Result<Vec<SyncOutcome>> {
    let source = root.join(".llmignore");
    let rules = std::fs::read_to_string(&source).map_err(|_| {
        anyhow::anyhow!(
            "no .llmignore at {} - run `llmignore init` first",
            source.display()
        )
    })?;
    if rules.trim().is_empty() {
        bail!("{} is empty - nothing to sync", source.display());
    }

    let contents = format!("{GENERATED_HEADER}\n\n{}", rules.trim_start());

    let mut outcomes = Vec::with_capacity(TARGETS.len());
    for target in TARGETS {
        let path = root.join(target.filename);
        let owned_by_us = match std::fs::read_to_string(&path) {
            Ok(existing) => existing.contains(GENERATED_HEADER),
            Err(_) => true, // does not exist yet
        };

        if path.exists() && !owned_by_us && !force {
            outcomes.push(SyncOutcome {
                filename: target.filename,
                tool: target.tool,
                status: SyncStatus::SkippedExists,
            });
            continue;
        }

        std::fs::write(&path, &contents).with_context(|| format!("writing {}", path.display()))?;
        outcomes.push(SyncOutcome {
            filename: target.filename,
            tool: target.tool,
            status: SyncStatus::Written,
        });
    }
    Ok(outcomes)
}
